#!/usr/bin/env python

import sys
import getopt
from itertools import izip_longest

opts, args = getopt.getopt(sys.argv[1:], 'd:', '--delimiter')
delimiter=' ||| '

for joined_line in izip_longest(*(open(a) for a in args)):
  print delimiter.join(map(lambda x: str.strip(x) if x else " ", joined_line))

